/**
 * Video Learning API - Based on blocksec.json specification
 *
 * Endpoints:
 * - /video/get-video-all-info - Get all videos with progress status
 * - /video/report-progress-and-unlock - Report watch progress and unlock next video
 * - /video/get_play_url - Get specific video play URL
 */

import { API_BASE_URL } from "../types";
import { getAuthHeaders } from "../utils";

// Video API base URL (same as main API)
const VIDEO_API_URL = API_BASE_URL;

// Video info from API response
export interface VideoInfo {
  video_id: string;
  video_name: string;
  video_desc: string;
  video_duration: number; // seconds
  point_reward: number;
  sort_order: number;
  can_play: boolean;
  is_received: boolean;
  play_url: string;
  unlock_msg: string;
}

// Response from get-video-all-info
export interface VideoListResponse {
  video_list: VideoInfo[];
  can_unlock_next: boolean;
  unlock_next_msg: string;
}

// Progress report request
export interface ProgressReportRequest {
  video_id: string;
  watch_record_id: string; // UUID generated by client
  is_ended: boolean;
  client_timestamp: number; // Unix timestamp in seconds
}

// Progress report response
export interface ProgressReportResponse {
  triggered: boolean;
  timestamp: number;
  tip?: string;
  actual_watch_seconds?: number;
  video_duration?: number;
  reward_point?: number;
  unlock_next_success?: boolean;
  unlock_next_msg?: string;
  reason?: string;
}

// Play URL response
export interface PlayUrlResponse {
  play_url: string;
  video_id: string;
}

// Generate UUID for watch_record_id
export function generateWatchRecordId(): string {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
    const r = Math.random() * 16 | 0;
    const v = c === 'x' ? r : (r & 0x3 | 0x8);
    return v.toString(16);
  });
}

// Get current timestamp in seconds
export function getCurrentTimestamp(): number {
  return Math.floor(Date.now() / 1000);
}

/**
 * Get all videos with their progress status
 * @param videoId Optional - get specific video info
 */
export async function getAllVideosInfo(videoId?: string): Promise<VideoListResponse> {
  const headers = getAuthHeaders();

  const response = await fetch(`${VIDEO_API_URL}/video/get-video-all-info`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ...headers,
    },
    body: videoId ? JSON.stringify({ video_id: videoId }) : JSON.stringify({}),
  });

  const data = await response.json();

  if (data.status === "error") {
    throw new Error(data.message || "Failed to fetch video info");
  }

  return data.data;
}

/**
 * Report video progress and potentially unlock next video
 *
 * Flow:
 * 1. Call with is_ended=false at video start to record start timestamp
 * 2. Call with is_ended=true at video end to validate watch time and unlock next
 *
 * @param request Progress report request
 */
export async function reportProgressAndUnlock(
  request: ProgressReportRequest
): Promise<ProgressReportResponse> {
  const headers = getAuthHeaders();

  const response = await fetch(`${VIDEO_API_URL}/video/report-progress-and-unlock`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ...headers,
    },
    body: JSON.stringify(request),
  });

  const data = await response.json();

  if (data.status === "error" && !data.data?.triggered) {
    throw new Error(data.message || "Progress report failed");
  }

  return {
    ...data.data,
    message: data.message,
  };
}

/**
 * Get play URL for a specific video
 * @param videoId The video ID to get URL for
 */
export async function getPlayUrl(videoId: string): Promise<PlayUrlResponse> {
  const headers = getAuthHeaders();

  const response = await fetch(`${VIDEO_API_URL}/video/get_play_url`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ...headers,
    },
    body: JSON.stringify({ video_id: videoId }),
  });

  const data = await response.json();

  if (data.status === "error") {
    throw new Error(data.message || "Failed to get play URL");
  }

  return data.data || data;
}

// ============================================
// Helper functions for video player component
// ============================================

export interface VideoSession {
  videoId: string;
  watchRecordId: string;
  startTimestamp: number;
  videoDuration: number;
  pointReward: number;
}

/**
 * Start watching a video - call this when user starts playback
 */
export async function startWatching(video: VideoInfo): Promise<VideoSession> {
  const watchRecordId = generateWatchRecordId();
  const startTimestamp = getCurrentTimestamp();

  // Report initial progress to backend
  await reportProgressAndUnlock({
    video_id: video.video_id,
    watch_record_id: watchRecordId,
    is_ended: false,
    client_timestamp: startTimestamp,
  });

  return {
    videoId: video.video_id,
    watchRecordId,
    startTimestamp,
    videoDuration: video.video_duration,
    pointReward: video.point_reward,
  };
}

/**
 * Complete watching a video - call this when video ends
 */
export async function completeWatching(session: VideoSession): Promise<{
  success: boolean;
  pointsEarned: number;
  unlockNext: boolean;
  message: string;
}> {
  const endTimestamp = getCurrentTimestamp();

  const result = await reportProgressAndUnlock({
    video_id: session.videoId,
    watch_record_id: session.watchRecordId,
    is_ended: true,
    client_timestamp: endTimestamp,
  });

  return {
    success: result.triggered,
    pointsEarned: result.reward_point || 0,
    unlockNext: result.unlock_next_success || false,
    message: result.unlock_next_msg || (result as any).message || "",
  };
}

// Legacy exports for backward compatibility
export type { VideoInfo as VideoProgressData };
export { getAllVideosInfo as getVideoProgress };
